# Site settings
theme: jekyll-theme-primer
title: 'Task & Reminder Management'
description: 'This project involves a Google Apps Script designed to streamline and automate various tasks within Google Sheets.'
